[build]
builder = "dockerfile"

[deploy]
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[environments.production]
[environments.production.variables]
NODE_ENV = "production"
PORT = "3000"

[environments.development]
[environments.development.variables]
NODE_ENV = "development"
PORT = "3000"
